### ISSUE TITLE
Player-owned hostile and neutral tokens are given the wrong border color in v12

### ISSUE THREAD

**Issue by BoltsJ** [theripper93/combat-tracker-dock#56]
In v12, PARTY token color is only applied if the token is both player owned and FRIENDLY disposition, as opposed to v11 and earlier where the color was used for any player-owned token. 

Steps to reproduce:
1. Create an Actor and set it to have a player owner
2. Set the token for the actor to have neutral or hostile disposition
3. Place a token on a scene and observe that the token has a yellow (neutral) or red (hostile) border
4. Add the token to a combat and observe that the disposition color on the card is green instead of matching the token.

![Screenshot from 2024-08-04 15-31-41](https://github.com/user-attachments/assets/ea353a94-82c5-45dd-8190-6f9cceba4e91)

**Comment by theripper93** [comment]
Owned actors use the separate "Party" color constant. This was never changed forever as far as i can recall

```js
    getBorderColor(tokenDocument) {
        if (!game.settings.get(MODULE_ID, "showDispositionColor") || !tokenDocument) return "#000";
        let color;
        const d = tokenDocument.disposition;
        const colors = CONFIG.Canvas.dispositionColors;
        if (!game.user.isGM && this.isOwner) color = colors.CONTROLLED;
        else if (this.actor?.hasPlayerOwner) color = colors.PARTY;
        else if (d === CONST.TOKEN_DISPOSITIONS.FRIENDLY) color = colors.FRIENDLY;
        else if (d === CONST.TOKEN_DISPOSITIONS.NEUTRAL) color = colors.NEUTRAL;
        else if (d === CONST.TOKEN_DISPOSITIONS.HOSTILE) color = colors.HOSTILE;
        else if (d === CONST.TOKEN_DISPOSITIONS.SECRET && this.isOwner) color = colors.SECRET;
        else color = colors.NEUTRAL;
        color = new Color(color).toString();
        return color;
    }
```

**Comment by theripper93** [comment]
Note that this is intentional and not a bug, it's so that player owned tokens are always recognized since many don't use the "fancy border"

**Comment by BoltsJ** [comment]
It was changed in foundry v12, but not documented in the patch notes. You can check in `client/pixi/placeables/token.js` line 1252, and yeah, I'm pretty sure that it was previously based only on ownership since at least v6.

**Comment by BadIdeasBureau** [comment]
In general, I'd assume that if a GM has set a token to hostile & has a player owner, there's probably a reason for that, and it probably makes sense for them to be counted on the enemy side for the combat tracker.

As Bolts says, and as shown in the screenshot on the issue, this is now the Foundry default (even if it got missed from the patch notes)

If you assume a player owned hostile token is supposed to be an enemy then the GM can override that by changing the token to friendly, whereas if you assume it's in the party whatever the disposition, then the GM has no way to get around that (if the token is "supposed" to be player owned and hostile).

In LANCER (the game I run at the moment) the potential cases where I can see "player owned but hostile" coming about are basically "PC is piloting an NPC mech due to story shenanigans" or "player is controlling one of the OPFOR" (e.g. because they're at session but their PC isn't in the story at the moment, and the GM wants to give them something to do).  In the former case, expecting the GM to swap them to friendly makes sense to me (and likely reduces wierdness with other modules which might be using disposition), and in the latter they aren't in the party anyway.

For something like D&D, the equivalent to a PC piloting an NPC mech would be a summon/polymorph or similar - again, not unreasonable to expect the GM (or the module handling the summoning) to change it to friendly, IMO.

For my particular use case, the current behaviour is a minor annoyance at the moment and likely to be more annoying later - I run with Material Plane (using IR tracking to move physical tokens on the screen), which means that the TV user needs to a) have control over any token that needs to move via MP, and b) not be a GM (so the players don't see any hidden notes/seeker mines/ etc on the big screen), so my combat tracker ends with everything showing as in the party, which is very unhelpful.

**Comment by theripper93** [comment]
Ah, i see - updated to match foundry default getTokenColor function
